name: Github Release

on:
  release:
    types:
      - created
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create archives
        run: sudo ./create_cnapy_projects_zip.sh

      - name: Upload assets
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Newline-delimited list of path globs for asset files to upload
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
